# Project: 
#   bootstrap 

# Purpose: 
#   This Travis continuous integration file is use to build and test boostrap
#   software written in Haskell.

language: ruby

os:
  - linux

rvm:
  - 2.1.3

notifications:
  email: false
  slack: allanconsulting:SDtIBjXdzbkBxeprTBsUIRbM
