# Project: emend
language: ruby
cache:
  bundler: true
dist: trusty
sudo: false
rvm:
- 2.3.4
before_script:
- bundle exec rake clean
script:
- bundle exec rake
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qkEmbcg/Bx0TT+WpcaWDWTlIoLzU+CXfBAF3zocm2vE91w+l6DupOZ3w8di51JdoJ0jlo9d94DDdW4dFSi/c/0QjduAUd5lEZpXsPffcIT934O0vq/Z172hJBUQHpJ9LKQS3KGXFrN3+XgSBOmI/IvNJRJEYSgqds9yQsem6IaBq4U8x4CrK/FJyLR8oGvpGO0trigWmQznrvqPpuYejxfhdxkllokGxKzHFACIg0DGAM4MPPvqVm1dYKWWGZaeOzbLPP/yO9Y0TklgJ27sWzsZKAOkfuGj4okpmOrjSEtDiP4tHb+dyyuXakLpCYvd5CIuaI5jaat1sWlUwXAo1RuvsGlpuQAJn+RO3zrYUP2B0V8qhM3rM2EjStloNCZ97/xItETgZHT7uo5npjDK6TAvaYSKwDlbgw/MTEfp7U1Zv33gngFmRjV5fSDWl17TxWlQyqeExLRymDuxzhGJzvJ2y0nwEbPzbpv1x3GzlOxMAMVuQxLrNwazo1w3bcx0ftbxNT6agt5F9XVtWlT0NyhmJHApFu/DJTMpOxdVbbmmWGByELEPgL6EULSP6vTq9IqRPgxL5KevzsvUUzx4rAfluu8A/6qkEHB94455AiQaah4b01bYft8eY6YDwW9SIQA/+30w3E0ZBUf7Mz5eMtpvAjqx8+NWQhLmMrEj6iv4=
  file: README.md
  on:
    tags: true
    branch: master
    repo: Traap/emend
notifications:
  email: false
  slack: allanconsulting:kkNikw4bLEJRZwBRJmP5YSPd
