# Project: 
#   bootstrap 

# Purpose: 
#   This Travis continuous integration file is use to build and test boostrap
#   software written in Haskell.

language: haskell 

sudo: required

ghc: 
  - 7.8

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal

script:
 - cabal build

notifications:
  email: false
  slack: allanconsulting:SDtIBjXdzbkBxeprTBsUIRbM
